# Generated by Django 4.0 on 2021-12-23 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case', models.CharField(max_length=250)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PackageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_package_rate', models.FloatField()),
                ('premimum_package_rate', models.FloatField()),
                ('ultra_package_rate', models.FloatField(blank=True)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usecase')),
            ],
        ),
    ]
